import type { Metadata } from "next";
import { Amatic_SC } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "@/providers/react-query-provider";

const amatic = Amatic_SC({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={amatic.className}>
        <ReactQueryProvider>{children}</ReactQueryProvider>
      </body>
    </html>
  );
}
